<?php 
// Spades, Hearts, Diamonds, Clubs
    $deck = [
        //SPADES
        ["value" => 11, "type" => "spades", "reference" => "A"],
        ["value" => 2, "type" => "spades", "reference" => 2],
        ["value" => 3, "type" => "spades", "reference" => 3],
        ["value" => 4, "type" => "spades", "reference" => 4],
        ["value" => 5, "type" => "spades", "reference" => 5],
        ["value" => 6, "type" => "spades", "reference" => 6],
        ["value" => 7, "type" => "spades", "reference" => 7],
        ["value" => 8, "type" => "spades", "reference" => 8],
        ["value" => 9, "type" => "spades", "reference" => 9],
        ["value" => 10, "type" => "spades", "reference" => 10],
        ["value" => 10, "type" => "spades", "reference" => "J"],
        ["value" => 10, "type" => "spades", "reference" => "Q"],
        ["value" => 10, "type" => "spades", "reference" => "K"],
        //HEARTS
        ["value" => 11, "type" => "Hearts", "reference" => "A"],
        ["value" => 2, "type" => "Hearts", "reference" => 2],
        ["value" => 3, "type" => "Hearts", "reference" => 3],
        ["value" => 4, "type" => "Hearts", "reference" => 4],
        ["value" => 5, "type" => "Hearts", "reference" => 5],
        ["value" => 6, "type" => "Hearts", "reference" => 6],
        ["value" => 7, "type" => "Hearts", "reference" => 7],
        ["value" => 8, "type" => "Hearts", "reference" => 8],
        ["value" => 9, "type" => "Hearts", "reference" => 9],
        ["value" => 10, "type" => "Hearts", "reference" => 10],
        ["value" => 10, "type" => "Hearts", "reference" => "J"],
        ["value" => 10, "type" => "Hearts", "reference" => "Q"],
        ["value" => 10, "type" => "Hearts", "reference" => "K"],
        //DIAMONDS
        ["value" => 11, "type" => "Diamonds", "reference" => "A"],
        ["value" => 2, "type" => "Diamonds", "reference" => 2],
        ["value" => 3, "type" => "Diamonds", "reference" => 3],
        ["value" => 4, "type" => "Diamonds", "reference" => 4],
        ["value" => 5, "type" => "Diamonds", "reference" => 5],
        ["value" => 6, "type" => "Diamonds", "reference" => 6],
        ["value" => 7, "type" => "Diamonds", "reference" => 7],
        ["value" => 8, "type" => "Diamonds", "reference" => 8],
        ["value" => 9, "type" => "Diamonds", "reference" => 9],
        ["value" => 10, "type" => "Diamonds", "reference" => 10],
        ["value" => 10, "type" => "Diamonds", "reference" => "J"],
        ["value" => 10, "type" => "Diamonds", "reference" => "Q"],
        ["value" => 10, "type" => "Diamonds", "reference" => "K"],
        //CLUBS
        ["value" => 11, "type" => "Clubs", "reference" => "A"],
        ["value" => 2, "type" => "Clubs", "reference" => 2],
        ["value" => 3, "type" => "Clubs", "reference" => 3],
        ["value" => 4, "type" => "Clubs", "reference" => 4],
        ["value" => 5, "type" => "Clubs", "reference" => 5],
        ["value" => 6, "type" => "Clubs", "reference" => 6],
        ["value" => 7, "type" => "Clubs", "reference" => 7],
        ["value" => 8, "type" => "Clubs", "reference" => 8],
        ["value" => 9, "type" => "Clubs", "reference" => 9],
        ["value" => 10, "type" => "Clubs", "reference" => 10],
        ["value" => 10, "type" => "Clubs", "reference" => "J"],
        ["value" => 10, "type" => "Clubs", "reference" => "Q"],
        ["value" => 10, "type" => "Clubs", "reference" => "K"]
    ]
?>