<?php 
// Spades, Hearts, Diamonds, Clubs
    $deck = [
        //SPADES
        ["value" => 11, "type" => "&#x2660;", "reference" => "A"],
        ["value" => 2, "type" => "&#x2660;", "reference" => 2],
        ["value" => 3, "type" => "&#x2660;", "reference" => 3],
        ["value" => 4, "type" => "&#x2660;", "reference" => 4],
        ["value" => 5, "type" => "&#x2660;", "reference" => 5],
        ["value" => 6, "type" => "&#x2660;", "reference" => 6],
        ["value" => 7, "type" => "&#x2660;", "reference" => 7],
        ["value" => 8, "type" => "&#x2660;", "reference" => 8],
        ["value" => 9, "type" => "&#x2660;", "reference" => 9],
        ["value" => 10, "type" => "&#x2660;", "reference" => 10],
        ["value" => 10, "type" => "&#x2660;", "reference" => "J"],
        ["value" => 10, "type" => "&#x2660;", "reference" => "Q"],
        ["value" => 10, "type" => "&#x2660;", "reference" => "K"],
        //HEARTS
        ["value" => 11, "type" => "&#x2665;", "reference" => "A"],
        ["value" => 2, "type" => "&#x2665;", "reference" => 2],
        ["value" => 3, "type" => "&#x2665;", "reference" => 3],
        ["value" => 4, "type" => "&#x2665;", "reference" => 4],
        ["value" => 5, "type" => "&#x2665;", "reference" => 5],
        ["value" => 6, "type" => "&#x2665;", "reference" => 6],
        ["value" => 7, "type" => "&#x2665;", "reference" => 7],
        ["value" => 8, "type" => "&#x2665;", "reference" => 8],
        ["value" => 9, "type" => "&#x2665;", "reference" => 9],
        ["value" => 10, "type" => "&#x2665;", "reference" => 10],
        ["value" => 10, "type" => "&#x2665;", "reference" => "J"],
        ["value" => 10, "type" => "&#x2665;", "reference" => "Q"],
        ["value" => 10, "type" => "&#x2665;", "reference" => "K"],
        //DIAMONDS
        ["value" => 11, "type" => "&#x2666;", "reference" => "A"],
        ["value" => 2, "type" => "&#x2666;", "reference" => 2],
        ["value" => 3, "type" => "&#x2666;", "reference" => 3],
        ["value" => 4, "type" => "&#x2666;", "reference" => 4],
        ["value" => 5, "type" => "&#x2666;", "reference" => 5],
        ["value" => 6, "type" => "&#x2666;", "reference" => 6],
        ["value" => 7, "type" => "&#x2666;", "reference" => 7],
        ["value" => 8, "type" => "&#x2666;", "reference" => 8],
        ["value" => 9, "type" => "&#x2666;", "reference" => 9],
        ["value" => 10, "type" => "&#x2666;", "reference" => 10],
        ["value" => 10, "type" => "&#x2666;", "reference" => "J"],
        ["value" => 10, "type" => "&#x2666;", "reference" => "Q"],
        ["value" => 10, "type" => "&#x2666;", "reference" => "K"],
        //Clubs;
        ["value" => 11, "type" => "&#x2663;", "reference" => "A"],
        ["value" => 2, "type" => "&#x2663;", "reference" => 2],
        ["value" => 3, "type" => "&#x2663;", "reference" => 3],
        ["value" => 4, "type" => "&#x2663;", "reference" => 4],
        ["value" => 5, "type" => "&#x2663;", "reference" => 5],
        ["value" => 6, "type" => "&#x2663;", "reference" => 6],
        ["value" => 7, "type" => "&#x2663;", "reference" => 7],
        ["value" => 8, "type" => "&#x2663;", "reference" => 8],
        ["value" => 9, "type" => "&#x2663;", "reference" => 9],
        ["value" => 10, "type" => "&#x2663;", "reference" => 10],
        ["value" => 10, "type" => "&#x2663;", "reference" => "J"],
        ["value" => 10, "type" => "&#x2663;", "reference" => "Q"],
        ["value" => 10, "type" => "&#x2663;", "reference" => "K"]
    ]
?>